openapi: 3.0.1
paths:
  /login:
    post:
      tags:
      - Authentication
      summary: Login with username and password
      description: Authenticates a user with username and password and returns JWT
        tokens
      operationId: login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/UsernamePasswordCredentials"
          application/json:
            schema:
              oneOf:
              - $ref: "#/components/schemas/UsernamePasswordCredentials"
              - type: object
                properties:
                  credentials:
                    $ref: "#/components/schemas/UsernamePasswordCredentials"
            example: null
        required: true
      responses:
        "200":
          description: login 200 response
          content:
            application/json:
              example: null
        "401":
          description: Invalid credentials
  /logout:
    get:
      operationId: indexGet
      responses:
        "200":
          description: indexGet 200 response
          content:
            application/json:
              schema:
                type: object
    post:
      operationId: index
      responses:
        "200":
          description: index 200 response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    UsernamePasswordCredentials:
      required:
      - password
      - username
      type: object
      properties:
        identity:
          type: string
          nullable: true
        password:
          minLength: 1
          type: string
        secret:
          type: string
          nullable: true
        username:
          minLength: 1
          type: string
