#tag::micronaut[]
micronaut:
  application:
    name: auth-service
  server:
    port: 8100
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /v3/api-docs/**
        access: isAnonymous()
      - pattern: /login
        access: isAnonymous()
      - pattern: /prometheus
        access: isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
        generator:
          refresh-token:
            enabled: true
            secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
      generator:
        access-token:
          expiration: 360000
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 1m
    binders:
      database:
        enabled: true
        include:
          - "hikari"
          - "jdbc"
    distribution:
      percentiles-histogram:
        hikaricp.connections: true
        hikaricp.connections.idle: true
        hikaricp.connections.active: true
        hikaricp.connections.pending: true
        hikaricp.connections.max: true
        hikaricp.connections.min: true
        hikaricp.connections.timeout: true
        hikaricp.connections.creation: true
        hikaricp.connections.acquire: true
        hikaricp.connections.usage: true
        jdbc.connections.active: true
        jdbc.connections.idle: true
        jdbc.connections.max: true
        jdbc.connections.min: true
        jdbc.connections.timeout: true
        jdbc.connections.creation: true
        jdbc.connections.acquire: true
        jdbc.connections.usage: true
  endpoints:
    prometheus:
      enabled: true
      sensitive: false
#end::micronaut[]

#tag::database[]
datasources:
  default:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
#end::database[]

#tag::jaeger[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.01 # <1>
#end::jaeger[]
