#tag::micronaut[]
micronaut:
  application:
    name: auth-service
  server:
    port: 8090
#end::micronaut[]

#tag::zipkin[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1 # <1>
#end::zipkin[]
